stages:
  - build
  - deploy

variables:
  CONTAINER_IMAGE_BUILT: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
  WIKI_URL_HOMOLOG: wiki-homolog.trt20.jus.br
  WIKI_INTRA_HOMOLOG: wiki-homolog.trt20.intra
  WIKI_URL: wiki.trt20.jus.br
  WIKI_INTRA: wiki.trt20.intra

build:
  image: docker:latest
  stage: build
  only:
    - tags
  services:
    - docker:dind
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - docker pull ${CI_REGISTRY_IMAGE}:${CI_DEFAULT_BRANCH} || true
    - docker pull ${CONTAINER_IMAGE_BUILT} || true
    - docker build --cache-from ${CI_REGISTRY_IMAGE}:${CI_DEFAULT_BRANCH} --cache-from ${CONTAINER_IMAGE_BUILT} -t ${CONTAINER_IMAGE_BUILT} .
    - docker push ${CONTAINER_IMAGE_BUILT}

deploy_homolog:
  stage: deploy
  only:
    - tags
  image: dtzar/helm-kubectl
  variables:
    URL: "wiki-homolog.trt20.jus.br"
  environment:
    name: homolog
    url: http://${URL}
    on_stop: stop_homolog
    kubernetes:
      namespace: default
  script:
    - echo "Deploy do ${APP_NAME} em homolog"
    - helm upgrade ${APP_NAME} chart/wiki
        --install
        --set gitlab.app=$CI_PROJECT_PATH_SLUG
        --set gitlab.env=$CI_ENVIRONMENT_SLUG
        --set image=$CONTAINER_IMAGE_BUILT
        --set url=$WIKI_URL_HOMOLOG
        --set url_intra=$WIKI_INTRA_HOMOLOG
    - helm get manifest ${APP_NAME} > ${CI_PROJECT_NAME}-${CI_ENVIRONMENT_NAME}.yaml
  artifacts:
    paths:
      - ${CI_PROJECT_NAME}-${CI_ENVIRONMENT_NAME}.yaml

stop_homolog:
  stage: deploy
  only:
    - tags
  image: dtzar/helm-kubectl
  variables:
    GIT_STRATEGY: none
  script:
    - echo "Removendo ${APP_NAME} da homolog"
    - helm uninstall ${APP_NAME}
  when: manual
  environment:
    name: homolog
    action: stop
    kubernetes:
      namespace: default
