apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      imagePullSecrets:
      - name: registrytrt20
      containers:
      - name: {{ .Release.Name }}
    spec:
      imagePullSecrets:
      - name: registrytrt20
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image }}
        imagePullPolicy: Always 
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 600
          timeoutSeconds: 2 
        ports:
        - containerPort: 80
        volumeMounts:
        - name: {{ .Release.Name }}-nfs
          mountPath: "/var/www/html/images"
        env:
        - name: DB_SERVER
          value: {{ .Values.config.db.server }}
        - name: DB_NAME
          value: {{ .Values.config.db.name }}
        - name: DB_USER
          value: {{ .Values.config.db.user }}
        - name: DB_PASSWORD
          value: {{ .Values.config.db.password }}
        - name: AD_USER
          value: {{ .Values.config.ad.user }}
        - name: AD_PASS
          value: {{ .Values.config.ad.pass }}
      volumes:
      - name: {{ .Release.Name }}-nfs
        persistentVolumeClaim:
          claimName: {{ .Values.config.volumes.wiki.pvc }}

