apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      imagePullSecrets:
      - name: registrytrt20
      containers:
      - name: {{ .Release.Name }}
    spec:
      imagePullSecrets:
      - name: registrytrt20
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image }}
        imagePullPolicy: Always 
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 600
          timeoutSeconds: 2 
        ports:
        - containerPort: 80
        volumeMounts:
        - name: {{ .Release.Name }}-nfs
          mountPath: "/var/www/html/images"
        env:
        - name: DB_TYPE
          value: "mysql"
        - name: DB_SERVER
          value: "10.20.0.163"
        - name: DB_NAME
          value: "mediawiki_homolog"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "12mudar34"
      volumes:
      - name: {{ .Release.Name }}-nfs
        persistentVolumeClaim:
          claimName: {{ .Values.config.volumes.wiki.pvc }}

